# docker-compose-build.yml
version: '3.3'

services:
  client:
    image: hangekinobaka/dvc-app-client:0.0.1
    build:
      context: .
      dockerfile: docker/client/Dockerfile.prod

  server:
    image: hangekinobaka/dvc-app-server:0.0.1
    build:
      context: .
      dockerfile: docker/server/Dockerfile.prod

