export const USERNAME_LEN = '15'

export const INVITE_CODE_LEN = '4'

export const API_STATUS = {
  API_CODE_FAIL: 0,
  API_CODE_SUCCESS: 1,
  API_CODE_NO_DATA: 2,
  API_CODE_ROOM_GEN_FAIL: 3,
  API_CODE_NO_ROOM: 4,
  API_CODE_ROOM_TAKEN: 5,
  API_CODE_ROOM_DESTROYED: 6
}