# Dockerfile
FROM node:alpine3.13

WORKDIR '/var/www/app'

COPY client/package*.json ./

RUN npm ci

COPY ./client/ .

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_ENDPOINT

ENV NEXT_PUBLIC_API_URL $NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_ENDPOINT $NEXT_PUBLIC_ENDPOINT

RUN ["npm", "run", "build"]
CMD ["npm", "run", "start"]