const GAME_STATUS = {
  USER_1_DRAW_INIT: 1,
  USER_2_DRAW_INIT: 2,
  USER_1_PUT_IN_LINE: 3,
  USER_2_PUT_IN_LINE: 4,
  USER_1_DRAW: 5,
  USER_2_DRAW: 6,
  USER_1_GUESS: 7,
  USER_2_GUESS: 8,
  USER_1_CHOOSE: 9,
  USER_2_CHOOSE: 10,
  USER_1_ANSWER: 11,
  USER_2_ANSWER: 12,
  USER_1_DRAG: 13,
  USER_2_DRAG: 14,
  USER_LEFT: 15,
  USER_EXIT: 16,
  PUT_IN_LINE_INIT: 17,
  USER_1_WIN: 18,
  USER_2_WIN: 19,
  USER_1_WAIT_RESTART: 20,
  USER_2_WAIT_RESTART: 21,
};

const API_STATUS = {
  API_CODE_FAIL: 0,
  API_CODE_SUCCESS: 1,
  API_CODE_NO_DATA: 2,
  API_CODE_ROOM_GEN_FAIL: 3,
  API_CODE_NO_ROOM: 4,
  API_CODE_ROOM_TAKEN: 5,
  API_CODE_ROOM_DESTROYED: 6
};

module.exports = {
  GAME_STATUS,
  API_STATUS
};