const GAME_STATUS = {
  USER_1_DRAW_INIT: 1,
  USER_2_DRAW_INIT: 2,
  USER_1_DRAG_INIT: 3,
  USER_2_DRAG_INIT: 4,
  USER_1_DRAW: 5,
  USER_2_DRAW: 6,
  USER_1_GUESS_MUST: 7,
  USER_2_GUESS_MUST: 8,
  USER_1_GUESS: 9,
  USER_2_GUESS: 10,
  USER_1_ANSWER: 11,
  USER_2_ANSWER: 12,
  USER_1_DRAG: 13,
  USER_2_DRAG: 14,
  USER_LEFT: 15,
  USER_EXIT: 16
};

module.exports = {
  GAME_STATUS
};